### ISSUE TITLE
mypy crashing upon startup

### ISSUE THREAD

**Issue by joe-p** [algorandfoundation/algokit-cli#186]
Starting VScode in the template folder after installing the recommended extensions results in this error from MyPy. I'm using the beaker v1 template: https://github.com/algorandfoundation/algokit-beaker-default-template/tree/ecfb03ee424fad1177249190979f231953ac3d40

I'm not sure if this is strictly algokit related or not but figured if I run into other devs might as well. 

```
❯ algokit doctor
timestamp: 2023-02-24T21:57:40+00:00
AlgoKit: 0.3.1
AlgoKit Python: 3.11.1 (main, Dec 23 2022, 09:25:23) [Clang 14.0.0 (clang-1400.0.29.202)] (location: /Users/joe/.local/pipx/venvs/algokit)
OS: macOS-12.6-arm64-arm-64bit
docker: 20.10.18
docker compose: 2.15.1
git: 2.37.0
python: 3.10.4 (location: /Users/joe/.asdf/shims/python)
python3: 3.10.4 (location: /Users/joe/.asdf/shims/python3)
pipx: 1.1.0
poetry: 1.3.2
node: 16.15.0
npm: 8.5.5
brew: 4.0.1

If you are experiencing a problem with AlgoKit, feel free to submit an issue via:
https://github.com/algorandfoundation/algokit-cli/issues/new
Please include this output, if you want to populate this message in your clipboard, run `algokit doctor -c`
```

VSCode MyPy output:
```
Mypy extension activated, version 0.2.3
Registering listener for interpreter changed event
Listener registered
[1] Check folder: /Users/joe/git/joe-p/beaker-v1-test
[1] Using config file: pyproject.toml
Activation complete
[1] Received python path from Python extension: /Users/joe/.asdf/shims/python
[1] Running dmypy in folder /Users/joe/git/joe-p/beaker-v1-test
/Users/joe/.asdf/shims/python -m mypy.dmypy --status-file '/Users/joe/Library/Application Support/Code/User/workspaceStorage/ecd165ebb0157b1d9de6da61568d317b/matangover.mypy/dmypy-2352482ba7f51226eff0157cddeabe892f51deb0-52295.json' run --log-file '/Users/joe/Library/Application Support/Code/User/workspaceStorage/ecd165ebb0157b1d9de6da61568d317b/matangover.mypy/dmypy-2352482ba7f51226eff0157cddeabe892f51deb0.log' -- --show-column-numbers --no-error-summary --no-pretty --no-color-output --config-file pyproject.toml --python-executable /Users/joe/.asdf/shims/python
[1] stdout:
Daemon started

[1] stderr:
Daemon crashed!
Traceback (most recent call last):
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/dmypy_server.py", line 229, in serve
    resp = self.run_command(command, data)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/dmypy_server.py", line 272, in run_command
    return method(self, **data)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/dmypy_server.py", line 331, in cmd_run
    return self.check(sources, is_tty, terminal_width)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/dmypy_server.py", line 388, in check
    res = self.initialize_fine_grained(sources, is_tty, terminal_width)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/dmypy_server.py", line 423, in initialize_fine_grained
    result = mypy.build.build(sources=sources,
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/build.py", line 254, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/build.py", line 2644, in dispatch
    graph = load_graph(sources, manager)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/build.py", line 2868, in load_graph
    newst = State(id=dep, path=None, source=None, manager=manager,
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/build.py", line 1888, in __init__
    self.parse_file()
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/build.py", line 2046, in parse_file
    self.tree = manager.parse_file(self.id, self.xpath, source,
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/build.py", line 788, in parse_file
    tree = parse(source, path, id, self.errors, options=options)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/parse.py", line 25, in parse
    return mypy.fastparse.parse(source,
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 168, in parse
    ).visit(ast)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 496, in visit_Module
    body = self.fix_function_overloads(self.translate_stmt_list(mod.body, ismodule=True))
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 729, in visit_ClassDef
    self.as_required_block(n.body, n.lineno),
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 509, in visit_FunctionDef
    return self.do_func_def(n)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 607, in do_func_def
    self.as_required_block(n.body, lineno),
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 329, in visit
    return visitor(node)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 797, in visit_For
    self.as_required_block(n.body, n.lineno),
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 439, in as_required_block
    b = Block(self.fix_function_overloads(self.translate_stmt_list(stmts)))
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 367, in translate_stmt_list
    node = self.visit(stmt)
  File "/Users/joe/.asdf/installs/python/3.10.4/lib/python3.10/site-packages/mypy/fastparse.py", line 327, in visit
    visitor = getattr(self, method)
AttributeError: 'ASTConverter' object has no attribute 'visit_Match'


[1] Error running mypy in /Users/joe/git/joe-p/beaker-v1-test: the mypy daemon crashed. This is probably a bug in mypy itself, see Output panel for details. The daemon will be restarted automatically.


```

**Comment by daniel-makerx** [comment]
Hi @joe-p, thanks for this report. It looks like the extension is using the global install of MyPy, rather than the one included in the projects .venv, I suspect in this case that is because the selected interpreter in VS Code is not the correct one. Can you try from the command palette `Cmd + Shift + P`  -> `Python: Select Interpreter` -> and select the `./.venv/bin/python` option, then see if the crash still occurs? This interpreter should be selected automatically in VS Code, but I think there might be an issue with this on MacOS, so will investigate that

**Comment by daniel-makerx** [comment]
Hi @joe-p , I worked out why the default interpreter setting wasn't being picked up for Mac OS, so both the beaker-v1 template and the main version of the template should now work correctly on new init'd projects. Note: There is still one existing quirk, where the interpreter is only picked up on the 2nd launch

**Comment by kcelestinomaria** [comment]
Was this resolved? Facing same issue, but on Ubuntu(Linux) OS env, I tried selecting ```./.venv/bin/python3.10``` from my end, but still not resolved.

**Comment by daniel-makerx** [comment]
@kcelestinomaria This should be resolved if you are using the correct venv in a project generated from an AlgoKit template. The original error was due to the wrong interpreter being selected, so it was picking up an outdated install of mypy. If you are still experiencing the issue can you please provide the exact error and stacktrace?

**Comment by robdmoore** [comment]
Closing for now, but happy to re-open if we get more reports.
